package com.example.app.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import com.paoloesan.proyectomobile.R
import zed.rainxch.rikkaui.foundation.RikkaAccentPreset
import zed.rainxch.rikkaui.foundation.RikkaPalette
import zed.rainxch.rikkaui.foundation.RikkaStylePreset
import zed.rainxch.rikkaui.foundation.RikkaTheme
import zed.rainxch.rikkaui.foundation.rikkaTypography

/**
 * App theme generated by RikkaUI Design System Creator.
 *
 * Palette: Zinc
 * Accent: Yellow
 * Style: Default
 * Font: Inter
 */
@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val fontFamily = FontFamily(
        Font(R.font.inter_light, FontWeight.Light),
        Font(R.font.inter_regular, FontWeight.Normal),
        Font(R.font.inter_medium, FontWeight.Medium),
        Font(R.font.inter_semi_bold, FontWeight.SemiBold),
        Font(R.font.inter_bold, FontWeight.Bold),
        Font(R.font.inter_black, FontWeight.Black)
    )

    RikkaTheme(
        palette = RikkaPalette.Zinc,
        accent = RikkaAccentPreset.Green,
        isDark = isDark,
        preset = RikkaStylePreset.Vega,
        typography = rikkaTypography(fontFamily, scale = RikkaStylePreset.Default.typeScale),
        content = content,
    )
}
